# Generated by Django 5.2.5 on 2026-07-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_lockdownschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='admin_password',
        ),
    ]
