# Generated by Django 5.2.5 on 2026-07-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_test_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockdownschedule',
            name='emails_sent',
            field=models.BooleanField(default=False),
        ),
    ]
