# Generated by Django 5.2.5 on 2026-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedquestion',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
