# Generated by Django 5.2.5 on 2026-08-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_management', '0002_cachedquestion_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
