# Generated by Django 5.2.5 on 2026-08-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_management', '0004_pendingtestsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtestsubmission',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
