import axios from 'axios';

// 1. Read the Node Port from the .env file generated by cli.py!
const NODE_PORT = process.env.REACT_APP_NODE_PORT || '8000';
// Dynamically route to whatever IP the browser is currently at, eliminating localhost lock-in!
const NODE_URL = `http://${window.location.hostname}:${NODE_PORT}`;
const NODE_INFO_ENDPOINT = `${NODE_URL}/api/node_info/`;

const MAX_RETRIES = 10;
const BASE_DELAY_MS = 1000;

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export async function discoverServers(retries = MAX_RETRIES) {
  let lastError = null;

  for (let attempt = 1; attempt <= retries; attempt++) {
    try {
      const response = await axios.get(NODE_INFO_ENDPOINT, {
        timeout: 3000,
        headers: { 'Content-Type': 'application/json' },
      });

      const data = response.data;

      if (!data || !data.database_server) {
        throw new Error(
          'Invalid response from /api/node_info/: missing database_server field'
        );
      }

      const { ip, port } = data.database_server;

      if (!ip || !port || ip === 'Pending...') {
        if (attempt < retries) {
          throw new Error('Database server is still Pending discovery via Zeroconf. Retrying...');
        }
        
        console.warn('Database server is pending discovery. Proceeding in offline mode.');
        return {
          centralURL: `http://localhost:${NODE_PORT}`, // Fallback for offline mode
          backendURL: `http://localhost:${NODE_PORT}`, // Crucial: Use localhost because LAN IP drops when WiFi drops
          nodeInfo: data,
        };
      }

      // The Node found the Database via Zeroconf and tells React where it is!
      const centralURL = `http://${ip}:${port}`;
      
      // 2. FIX: Set the backendURL to the port we booted the node on
      const backendURL = NODE_URL; 

      return {
        centralURL,
        backendURL,
        nodeInfo: data,
      };
    } catch (error) {
      lastError = error;
      console.warn(
        `[ServerDiscovery] Attempt ${attempt}/${retries} failed:`,
        error.message
      );

      if (attempt < retries) {
        const delay = BASE_DELAY_MS * attempt;
        console.info(`[ServerDiscovery] Retrying in ${delay}ms...`);
        await sleep(delay);
      }
    }
  }

  throw new Error(
    `Server discovery failed after ${retries} attempts. Last error: ${lastError?.message || 'Unknown error'}. ` +
      'Make sure the backend server is running and accessible.'
  );
}